### PR TITLE
Added mapping to composer.json

### PR DESCRIPTION
**Pull request by hhirsch**

### CODE REVIEW

**Comment by mmenozzi** [comment]
Hi Henry,
thank you for your pull request.
One question before merge: why you added the preferred-install config?
Note that the config section is used only if it's a project's composer.json and pug-more/magento_italia is usually used as dependency.

**Comment by hhirsch** [comment]
@mmenozzi I am not sure if it influences how the dependencies are downloaded in this case. If it does I'd prefer dist over source. But maybe it is not getting applied anyhow. I never checked.

**Comment by mmenozzi** [comment]
@hhirsch as you can see here https://getcomposer.org/doc/04-schema.md#config, the `config` property of the schema is `root-only` (https://getcomposer.org/doc/04-schema.md#root-package). So, the `config` you added is ignored when this package is used as dependency (most of the times). Please, remove it so we can merge the PR.

**Comment by hhirsch** [comment]
@mmenozzi I will. Thanks for looking that up.

**Comment by hhirsch** [comment]
@mmenozzi Done. Thanks for supporting me.

**Comment by mmenozzi** [comment]
Thank you @hhirsch!

**Pull request merged**
